server:
  port: 8040
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xieqiong/springConfig/     # 配置git仓库的地址
          search-paths: cffex                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: xieqiong                                            # git仓库的账号
          password: xie377039